# Generated by Django 6.1.1 on 2026-09-12 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Event', 'Event Expenses'), ('Food', 'Food & Refreshments'), ('Transportation', 'Transportation'), ('Materials', 'Materials & Supplies'), ('Printing', 'Printing & Photocopy'), ('Equipment', 'Equipment'), ('Other', 'Other Expenses')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_no', models.CharField(blank=True, max_length=50)),
                ('recorded_by', models.CharField(default='Treasurer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('Monthly', 'Monthly Contribution'), ('Registration', 'Registration Fee'), ('Event', 'Event Fee'), ('Donation', 'Donation'), ('Other', 'Other Income')], default='Monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.CharField(default='Treasurer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.member')),
            ],
        ),
    ]
